variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:dind

stages:
  - build_docker

build_docker:
  stage: build_docker
  image: docker:dind
  script:
    - i=0; while [ "$i" -lt 12 ]; do docker info && break; sleep 5; i=$(( i + 1 )) ; done
    - docker info

    - apk add bash
    - registry_path=$CI_REGISTRY/infrastructure/base-jupyterlab-image/$CI_COMMIT_REF_NAME
    - registry_path_current=$registry_path:$CI_PIPELINE_ID
    - registry_path_latest=$registry_path:latest

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    - docker build --no-cache -t $registry_path_current .
    - docker tag $registry_path_current $registry_path_latest

    - docker push $registry_path_latest
    - docker push $registry_path_current

    # cleanup docker images from host docker images
    - docker rmi $registry_path_latest
    - docker rmi $registry_path_current
